### ISSUE TITLE
Pass projectId to BigQuery client

### ISSUE THREAD

**Issue by borft** [snowplow-incubator/snowplow-bigquery-loader#261]
It seems the loader does not honor the `ProjectId` that is set in  the config, when trying to determine the location of the dataset. In most use cases, this is probably not a problem, as the project can be (automatically) inferred from either the service account used, or perhaps the GCP project that is running the loader.

Setup:
- 2 GCP projects, ProjectA and ProjectB
- VM in GCP, ProjectA running the big query stream loader in a docker container (snowplow/snowplow-bigquery-streamloader:1.2.0)
- Big Query dataset, in ProjectB

The loader will attempt to resolve the dataset in ProjectA (where it is running), even when specifying the correct project in the server config (hocon). From my local laptop, it works fine, as the GCP BQ libraries seem to fall back to the project in the service account used, which points to the right project.

A workaround seems to be to set the `GCLOUD_PROJECT` variable in the container to the right project.

**Comment by dilyand** [comment]
Hi @borft , that is the intended behaviour. 

Here is the definition of the `projectId` field of the `config.hocon` file: 'Required. The GCP project in which all required Pub/Sub, BigQuery and GCS resources are hosted, eg `my-project`.'

We have not considered cross-project deployments before. What makes it necessary to deploy the loader in one project and have the dataset in another? We can consider making this easier if there's a strong use case. In the meantime, it's good that you've identified a workaround.

**Comment by timvansteenis** [comment]
We actually ran into the same issue just now. We have our BigQuery in another GCP project compared to our VM's (k8s). 

Would be great if we could override the default behaviour and target the BigQuery project.

**Comment by timvansteenis** [comment]
@borft that worked for us. But i'm wondering if this will ever "break" at some point. Also, the command to create the initial BigQuery table seems to respect the `projectId` setting.

**Comment by borft** [comment]
@timvansteenis totally agree. It now relies on the GCP / BQ libraries respecting the appropriate environment variables. If that every changes (as historically there are multiple: https://cloud.google.com/functions/docs/configuring/env-var#runtime_environment_variables_set_automatically), which is not unlikely, this may break.

At the very least I think the way it works now if confusing / ambiguous as the `project_id` setting is present in the config file.

**Comment by dilyand** [comment]
@borft , @timvansteenis Could you please help us understand what the need for this cross-project setup is?

We're operating under the assumption that you should keep all of your Snowplow pipeline in one project; and if you want to use the data in another project, you would be able to as BigQuery supports cross-project queries.

What are we missing?

**Comment by borft** [comment]
@dilyand In my case it's a bit of shared infrastructure, that is to say, part of the infrastructure running snowplow is in a shared project, where-as the data / BigQuery instance lives in different ones, depending on the environment.

That said, I do see your point (about consolidating all resources in one project). However, I do think, regardless of use case, it seems illogical to be able to configure a `project_id` in a config file, and then arbitrarily use it in some cases, but not in other cases. If the loader is to rely on the environment to infer the project, wouldn't it make more sense to do so in all cases (which would make the behaviour more deterministic across/between environments; gcp and non-gcp)?

**Comment by timvansteenis** [comment]
We have a different GCP project for our data team because we work with third party contractors who we don't want to give access to our primary account. Our primary account contains most of our applications and everything there is configured from Cloud Armor to monitoring for our self hosted applications, which we didn't want to setup in another project as well.

Of course we could setup snowplow to stream to BigQuery in our primary account, but that would also mean to configure our iAM policies again. It is easier for us just to target our existing BigQuery project in another GCP account.

**Comment by istreeter** [comment]
On balance I agree with @borft and @timvansteenis -- at least, we are being inconsistent in our use of `projectId`.

Or maybe it's GCP who is being inconsistent in their use of `projectId` in their APIs!  For example, it seems that GCP's [java pubsub client](https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/cloud/pubsub/v1/Publisher.html) requires us to specify `projectId`, whereas GCP's [BigQuery client](https://googleapis.dev/java/google-cloud-bigquery/latest/com/google/cloud/bigquery/BigQueryOptions.Builder.html) allows us to omit `projectId`, but with an option to set it if we want to.

It seems like a fairly easy change to call the `setProjectId` method [on the BigQuery options builder](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/1.2.0/modules/streamloader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/streamloader/Bigquery.scala#L80) and I cannot think of any down sides of making that change.

I'm afraid I don't see this as an urgent change, because there appears to be a workaround and it's a setup we never planned to support.  But I reckon we can include this whenever we make the next release.
