### ISSUE TITLE
FileLoads loadMode doesn't work

### ISSUE THREAD

**Issue by DimitrijeMixajlo** [snowplow-incubator/snowplow-bigquery-loader#335]
Based on [Setup guide](https://docs.snowplow.io/docs/destinations/warehouses-and-lakes/bigquery/snowplow-bigquery-loader-configuration-reference/#advanced-options), it should be possible to use batch file upload. However, we are using the following configuration:
```
  "loader": {
    "loadMode": {
      "type": "FileLoads"
      "frequency": 600
    }
   ...
```
and it looks we still have streaming inserts: load_tstamps are equally distributed and can't find any temp files on the server. 

Searching the code in the repo I didn't find any mention of FileLoads.
Is FileLoads mode implemented? Is there a way to unequivocally confirm which mode the loader is using?

Thank you!

**Comment by benjben** [comment]
Hi @DimitrijeMixajlo ,

`FileLoads` was only possible with [Dataflow](https://cloud.google.com/dataflow) variant of the loader, which we [deprecated](https://github.com/snowplow-incubator/snowplow-bigquery-loader/commit/69fce2e4375c85955a72d0a7e5ab9eaf88a62d21) recently. We had forgotten to update the docs, sorry about that, thank you for reporting it, it's fixed now.

Current asset only supports streaming inserts, but FYI we're considering unifying BigQuery loader our [other loaders](https://github.com/snowplow/snowplow-rdb-loader) (Redshift, Snowflake, Databricks), which would make it use `FileLoads` instead of streaming inserts.
