### ISSUE TITLE
Release 1.6.5

### ISSUE THREAD

**Issue by dboek** [snowplow-incubator/snowplow-bigquery-loader#350]
Do you know when you will release the version 1.6.5 ? It seems to solve the problem we have with the BigQuery loader, which gets stuck after a connection problem with BigQuery. This can currently only be solved on our side by restarting the whole java process.

**Comment by colmsnowplow** [comment]
Hi there @dboek - release 1.6.5 has been available since April. I've just released 1.6.6 today, which is exactly the same but updates the libraries in the image to avoid vulnerabilities. Best to use that.

After pushing that release, I've noticed that the badge on the repo never updated since 1.6.4 - perhaps this is what led you to believe it's not out yet. Apologies for that, unfortunately don't have space in my day to figure out why but I'm creating an issue for it now.

Closing this comment but of course come back to me if I've misunderstood something!

**Comment by dboek** [comment]
Perfect, thanks! Yes, I didn‘t see the badge under releases so I thought it is still not finished.
We are pulling the versioned jars on github during deploy. Should have just tried to download the jar by changing the name to 1.6.5 - thanks for your support, 1.6.5 solved our BigQuery Backoff error problem.
