### ISSUE TITLE
Fix badge in readme

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow-incubator/snowplow-bigquery-loader#354]
The badge in this repo's readme displays 1.6.4, but we're on 1.6.6. I'm not sure why this is happening, but we should fix it.

**Comment by jbeemster** [comment]
Its because the last release is still 1.6.4 -> https://github.com/snowplow-incubator/snowplow-bigquery-loader/releases

We need to select the latest tag and then create a release from it which will then update the badge accordingly (like so: https://github.com/snowplow-incubator/snowplow-bigquery-loader/releases/new?tag=1.6.6)

**Comment by colmsnowplow** [comment]
Of course. Our having automated this in other projects caused me to forget it existed at all. Thanks Josh!
