### ISSUE TITLE
Handle disallowed characters in column names

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow-incubator/snowplow-bigquery-loader#39]
BigQuery columns/fields [can only contain alphanumeric or underscore characters](https://cloud.google.com/bigquery/docs/schemas#column_names), however there are use cases whereby we have no control over different characters being in field names - for example, when integrating data from a vendor [like branch](https://docs.branch.io/exports/ua-webhooks/#sample-webhook-post-body-syntax), users can't always rename fields with different characters.

We might strip special characters, or maybe replace them with underscores to avoid clashes with other column names perhaps.

**Comment by chuwy** [comment]
Related: https://github.com/snowplow-incubator/schema-ddl/issues/45

**Comment by miike** [comment]
Since we ran into this issue recently here's a few things we've been thinking about.

- What is the behaviour when a user uploads a new schema containing special characters (special characters in BQ, columns beginning with a number in Redshift)? Should the behaviour be to accept, warn, replace or give the user one of these options?

- Does this mean that Iglu Server needs to be aware of the storage targets or should the behaviour be normalised across all storage targets instead? I imagine we'd want to aim for normalisation to avoid having subtly different data structures in any targets.

- Is the mutator / loader responsible for transforming incoming data or should the data go to to bad rows? How do we deal with existing schemas that may already contain special characters?

**Comment by dilyand** [comment]
Adding some details, suggesting that it might not be ideal dealing with this issue in the Loader or in schema DDL.

Branch is an example of a vendor which sends events via a webhook where Snowplow and Snowplow users have no control over the schema. The below would be valid for any such vendor.

When the event reaches Enrich, it must first pass validation against its schema, which is the original vendor-defined one with the unallowed chars. We later perform validation in the Loader as well. Any cleanup of the key names must happen after this Loader-side validation. However, we would then need a second validation step in the Loader, to ensure the tweaking went well.

Can we do the tweaking before the Loader-side validation? Yes, but then the event will fail to validate unless we also tweak the schema. However, we cannot know what the schema would be in advance for any possible 3rd-party event. We can infer what it should be programmatically, based on the original schema. But then we are introducing a second, undocumented, implicit version of this schema.

Keep in mind that in order to reach the Loader at all, the event must first pass validation upon entry into Enrich, so we cannot do away with that original schema. We also have no idea in Enrich what storage target the event should go on to -- and the original schema is a perfectly valid JSON schema and self-describing schema. It's only BQ that is not playing nicely.

So, if we are going to need a second, cleaned up version of the schema, it's much better to make it explicit and subject it to the same robust process of schema creation and maintenance that we already have.

A work around along those lines would include:
- Two versions of the schema in the Iglu repository, likely one would be `io.branch/event_name/jsonschema/1-0-0` (with original keys) and the other would be a `com.snowplowuser/event_name/jsonschema/1-0-0` (with cleaned up keys).
- When the event hits Enrich it gets validated against the `io.branch` schema.
- It then moves on to the enrichment steps, where an appropriately configured JS enrichment replaces the "buggy" payload *and* the schema with the `com.snowplowuser` version.
- The enriched event passes post-enrichment validation, which is now happening against the new schema.
- In the Loader validation again uses the new schema, as this is what is now attached to the event.
- The event is successfully loaded.

**Comment by miike** [comment]
> A work around along those lines would include:

I like this approach as it's reasonably similar to how the adapters function with the caveat that they are often performing transformations in addition to renaming / removing / adding columns.

One thing I've wondered about the "two-schema" model is whether it's possible to preserve both the original event and the transformed event within the same event (which becomes a bit difficult if it's related to invalid column names). I'm hoping BQ will fix this shortly - as they fixed unicode characters in table names late last year.

**Comment by chuwy** [comment]
@dilyand, @miike sorry I still don't follow why do we need the second schema and overall the approach seems very complex and ad-hoc to me.

I think the solution here is to simply converge unacceptable column names into a BQ-compatible format, e.g. `3h` into `_3h` or just `h`. This is what we do with snake case and kebab case and there's no guarantees at the moment of loading that original names will be preserved (kebab and snake case examples again).

There's just one additional step - checking that there are no collisions (renaming `3h` into `_3h`, while there's original `_3h` defined) - should be done on linting stage.

Vendors that don't have control over their schemas are out of considerations because anything that cannot be schema'ed is not getting into BQ at all or gets there as a string.

**Comment by dilyand** [comment]
> I think the solution here is to simply converge unacceptable column names into a BQ-compatible format, e.g. 3h into _3h or just h. 

Where is this happening? Loader, schema DDL, Enrich?

> There's just one additional step - checking that there are no collisions (renaming 3h into _3h, while there's original _3h defined) - should be done on linting stage.

Where is this happening? When linting with `igluctl`?

> Vendors that don't have control over their schemas are out of considerations because anything that cannot be schema'ed is not getting into BQ at all or gets there as a string.

Do you mean that users should accept they can't load Branch et al data in BigQuery unless as a long string? These events can be massive (the schema itself is huge). They need to be in a structured format, otherwise they are useless.

**Comment by chuwy** [comment]
> Where is this happening? Loader, schema DDL, Enrich?

Same as snake/kebab case. In Loader, but functionlity responsible for it is in Schema DDL.

> Where is this happening? When linting with igluctl?

Yes, or in Iglu Server. Linting functionality for both Iglu Server and igluctl is inside Schema DDL.

> Do you mean that users should accept they can't load Branch et al data in BigQuery unless as a long string?

Yes, but this limitation has nothing to do with special symbols, but rather with:

> They need to be in a structured format, otherwise they are useless.

We cannot have a BQ column at all if schema is not known.

**Comment by miike** [comment]
> I think the solution here is to simply converge unacceptable column names into a BQ-compatible format, e.g. `3h` into `_3h` or just `h`. This is what we do with snake case and kebab case and there's no guarantees at the moment of loading that original names will be preserved (kebab and snake case examples again).

I think this is doable but I'd be concerned about the amount of logic this would need to encapsulate and whether it would result in columns that are understandable e.g.,

_3h => h
_12h => ?
_24h => ?

This becomes less obvious when handling non-ASCII characters (not sure if this is outside the scope of this ticket) e.g., having a `météo` or `Погода` column.

>Yes, or in Iglu Server. Linting functionality for both Iglu Server and igluctl is inside Schema DDL.

I'm guessing the linting behaviour should be identical irrespective of downstream data source or would this be BQ specific? Linting will ensure that the columns can be created but it then no longer becomes possible to use the Iglu Webhook functionality without the addition of an adapter that transforms from the vendor webhook schema to the post-linted schema.

**Comment by dilyand** [comment]
Can schema DDL currently warn when linting with `igluctl` if you have keys `my-key` and `my_key` in the same schema?

> We cannot have a BQ column at all if schema is not known.

The schema is known. It just has characters that BQ doesn't like.

**Comment by chuwy** [comment]
> _3h => h
> _12h => ?
> _24h => ?

Two points here:

1. `_3h` is valid, as a column can start with underscore. Thus prepending with an underscore is better than just removing the offending character
2. I think there must be a linting step to prevent situations like this before publishing schemas (or if we just add `_` - we still want to know that there's no already defined `3h`/`_3h` pair, which could result in awkward `_3h` and `__3h`)

> This becomes less obvious when handling non-ASCII characters

And this is one of the reasons why I'm so much against making these common (there was a recent proposal in community to make Iglu vendor/name supporting unicode characters). As someone who's native language consists on non-ASCII characters I know how much PITA they can be. At the very least some DBs support them, some don't. And this point also brings us to a much broader topic:

> I'm guessing the linting behaviour should be identical irrespective of downstream data source or would this be BQ specific? 

We were discussing this with @ebedford420 a lot. At the inception of Iglu/SchemaVer, Snowplowes were overly optimistic to assume that there's some universal notion of a breaking change, but even within just 4 DBs we support this notion varies a lot. The most recent consensus was to:

1. Have atomic linters as we do in igluctl now (`minMaxCheck`, `maxLengthCheck` etc)
2. Have predefined sets of linters: `bigquery`, `redshift`, `snowflake`, `all` etc
3. Put users in charge of what sets they use with the strongest one by default
4. Iglu Server with a configured set can then derive SchemaVer and for example reject schemas with both `3h` and `12h` iff we decide to remove offending characters (but I still think that adding `_` is less harmful)



> Can schema DDL currently warn when linting with igluctl if you have keys my-key and my_key in the same schema?

It can, but it doesn't. We had this behavior since the inception.

> The schema is known. It just has characters that BQ doesn't like.

Sorry, misunderstood it. Then we still have an escping option. It's just the escaping algorithm we need to come up with. Which is 10 out 10 a lot easier than an additional schema.

**Comment by dilyand** [comment]
Just to make sure I understand you plan in full @chuwy. The workflow would be:
- 3rd-party vendor authors schema with unallowed (in BQ) chars
- user copies 3rd-party schema as is and uploads it to their iglu; linting gives a green light, unless there are "duplicate" keys
- 3rd-party vendor sends events via webhook that comply with its own schema
- enrich validates the event against the schema on iglu
- BQ loader validates the event against the schema on iglu
- before loading into BQ, schema ddl changes the names of the keys according to our custom logic that makes them BQ-compatible.

Am I missing something?

**Comment by chuwy** [comment]
So, I think the consensus here is to make BigQuery Loader change the column names on-fly from `3h` to `_3h`, i.e. prepend with an underscore.

@spenes when you'll be working on it - could you please check if it's easily double within Loader or we can implment this only in https://github.com/snowplow/schema-ddl/issues/45.

The only problem I'm worrying about is what to do if we already have `3h` and `_3h` in schema (super corner case though). I think these scenarios can be handled propertly only in schema-ddl. Also it's not covering non-ASCII yet, which can be a totally different ticket.

**Comment by dilyand** [comment]
Superseded by https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/197
